[tool.black]
line-length = 100

[tool.ruff]

# Default configuration for code validation
select = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
ignore = [
    "A003",
    "ANN101",
    "ANN102",
    "ANN201",
    "ANN204",
    "ANN401",
    "B008",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D106",
    "D107",
    "D212",
    "D211",
    "D203",
]

exclude = ["alembic/"]

# Default configuration for auto fixing
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []

# Default configuration for code checking
target-version = "py310"
line-length = 100

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]    # ignore asserts in tests

[tool.mypy]
python_version = "3.10"
exclude = ["alembic/"]
plugins = [
  "pydantic.mypy"
]

[[tool.mypy.overrides]]
module = ["celery.*"]
ignore_missing_imports = true
